# Generated by Django 4.2.10 on 2024-02-19 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_customuser_noteversionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteversionhistory',
            name='note',
        ),
        migrations.RemoveField(
            model_name='noteversionhistory',
            name='user',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='sharednote',
            old_name='shared_with',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='NoteVersionHistory',
        ),
    ]
